# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# This is a stub file - in production, this would be generated from common.proto

class HealthCheckRequest:
    pass

class HealthCheckResponse:
    def __init__(self):
        self.status = ""
        self.service_name = ""
        self.version = ""
        self.uptime_seconds = 0

class Timestamp:
    def __init__(self):
        self.seconds = 0
        self.nanos = 0 