# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import common_pb2 as common__pb2
import osint_pb2 as osint__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in osint_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class OSINTServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.HealthCheck = channel.unary_unary(
                '/cobra.osint.OSINTService/HealthCheck',
                request_serializer=common__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=common__pb2.HealthCheckResponse.FromString,
                _registered_method=True)
        self.GatherOSINT = channel.unary_unary(
                '/cobra.osint.OSINTService/GatherOSINT',
                request_serializer=osint__pb2.OSINTRequest.SerializeToString,
                response_deserializer=osint__pb2.OSINTResponse.FromString,
                _registered_method=True)
        self.GetShodanData = channel.unary_unary(
                '/cobra.osint.OSINTService/GetShodanData',
                request_serializer=osint__pb2.ShodanRequest.SerializeToString,
                response_deserializer=osint__pb2.ShodanResponse.FromString,
                _registered_method=True)
        self.GetCensysData = channel.unary_unary(
                '/cobra.osint.OSINTService/GetCensysData',
                request_serializer=osint__pb2.CensysRequest.SerializeToString,
                response_deserializer=osint__pb2.CensysResponse.FromString,
                _registered_method=True)
        self.GetVirusTotalData = channel.unary_unary(
                '/cobra.osint.OSINTService/GetVirusTotalData',
                request_serializer=osint__pb2.VirusTotalRequest.SerializeToString,
                response_deserializer=osint__pb2.VirusTotalResponse.FromString,
                _registered_method=True)
        self.GetWaybackData = channel.unary_unary(
                '/cobra.osint.OSINTService/GetWaybackData',
                request_serializer=osint__pb2.WaybackRequest.SerializeToString,
                response_deserializer=osint__pb2.WaybackResponse.FromString,
                _registered_method=True)
        self.GetDNSHistory = channel.unary_unary(
                '/cobra.osint.OSINTService/GetDNSHistory',
                request_serializer=osint__pb2.DNSHistoryRequest.SerializeToString,
                response_deserializer=osint__pb2.DNSHistoryResponse.FromString,
                _registered_method=True)
        self.GetHIBPData = channel.unary_unary(
                '/cobra.osint.OSINTService/GetHIBPData',
                request_serializer=osint__pb2.HIBPRequest.SerializeToString,
                response_deserializer=osint__pb2.HIBPResponse.FromString,
                _registered_method=True)


class OSINTServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GatherOSINT(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetShodanData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCensysData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVirusTotalData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWaybackData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDNSHistory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHIBPData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OSINTServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=common__pb2.HealthCheckRequest.FromString,
                    response_serializer=common__pb2.HealthCheckResponse.SerializeToString,
            ),
            'GatherOSINT': grpc.unary_unary_rpc_method_handler(
                    servicer.GatherOSINT,
                    request_deserializer=osint__pb2.OSINTRequest.FromString,
                    response_serializer=osint__pb2.OSINTResponse.SerializeToString,
            ),
            'GetShodanData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetShodanData,
                    request_deserializer=osint__pb2.ShodanRequest.FromString,
                    response_serializer=osint__pb2.ShodanResponse.SerializeToString,
            ),
            'GetCensysData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCensysData,
                    request_deserializer=osint__pb2.CensysRequest.FromString,
                    response_serializer=osint__pb2.CensysResponse.SerializeToString,
            ),
            'GetVirusTotalData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVirusTotalData,
                    request_deserializer=osint__pb2.VirusTotalRequest.FromString,
                    response_serializer=osint__pb2.VirusTotalResponse.SerializeToString,
            ),
            'GetWaybackData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWaybackData,
                    request_deserializer=osint__pb2.WaybackRequest.FromString,
                    response_serializer=osint__pb2.WaybackResponse.SerializeToString,
            ),
            'GetDNSHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDNSHistory,
                    request_deserializer=osint__pb2.DNSHistoryRequest.FromString,
                    response_serializer=osint__pb2.DNSHistoryResponse.SerializeToString,
            ),
            'GetHIBPData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHIBPData,
                    request_deserializer=osint__pb2.HIBPRequest.FromString,
                    response_serializer=osint__pb2.HIBPResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cobra.osint.OSINTService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cobra.osint.OSINTService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OSINTService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cobra.osint.OSINTService/HealthCheck',
            common__pb2.HealthCheckRequest.SerializeToString,
            common__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GatherOSINT(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cobra.osint.OSINTService/GatherOSINT',
            osint__pb2.OSINTRequest.SerializeToString,
            osint__pb2.OSINTResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetShodanData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cobra.osint.OSINTService/GetShodanData',
            osint__pb2.ShodanRequest.SerializeToString,
            osint__pb2.ShodanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCensysData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cobra.osint.OSINTService/GetCensysData',
            osint__pb2.CensysRequest.SerializeToString,
            osint__pb2.CensysResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetVirusTotalData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cobra.osint.OSINTService/GetVirusTotalData',
            osint__pb2.VirusTotalRequest.SerializeToString,
            osint__pb2.VirusTotalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetWaybackData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cobra.osint.OSINTService/GetWaybackData',
            osint__pb2.WaybackRequest.SerializeToString,
            osint__pb2.WaybackResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDNSHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cobra.osint.OSINTService/GetDNSHistory',
            osint__pb2.DNSHistoryRequest.SerializeToString,
            osint__pb2.DNSHistoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetHIBPData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cobra.osint.OSINTService/GetHIBPData',
            osint__pb2.HIBPRequest.SerializeToString,
            osint__pb2.HIBPResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
