"""Device model for CLI device registration and management.

Each device is identified by a UUID and associated with a user account.
Device limits are enforced based on subscription tier.
"""

from datetime import datetime
from typing import TYPE_CHECKING

from sqlalchemy import DateTime, ForeignKey, Integer, String, func
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.database import Base

if TYPE_CHECKING:
    from app.models.user import User


class Device(Base):
    """Registered device (CLI installation) model.

    Each device represents a unique CLI installation tied to a user account.
    Device limits per tier:
    - Free: 1 device
    - Starter: 2 devices
    - Pro: 3 devices
    - Enterprise: 500 devices

    Attributes:
        id: Primary key
        user_id: Foreign key to user account
        device_uuid: Unique device identifier (generated by CLI)
        device_name: User-friendly device name
        platform: Operating system (linux, darwin, win32)
        hostname: Machine hostname (for identification)
        last_seen: Last activity timestamp (updated on each API call)
        is_active: Active status (soft delete)
        created_at: Device registration timestamp
        updated_at: Last update timestamp
    """

    __tablename__ = "devices"

    # Primary key
    id: Mapped[int] = mapped_column(Integer, primary_key=True, index=True)

    # Foreign key to user
    user_id: Mapped[int] = mapped_column(
        Integer,
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,  # Index for fast user device lookups
    )

    # Device identification
    device_uuid: Mapped[str] = mapped_column(
        String(255),
        unique=True,
        index=True,
        nullable=False,
    )
    device_name: Mapped[str] = mapped_column(String(255), nullable=False)
    platform: Mapped[str | None] = mapped_column(String(50), nullable=True)  # linux, darwin, win32
    hostname: Mapped[str | None] = mapped_column(String(255), nullable=True)

    # Status and activity
    last_seen: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )
    is_active: Mapped[bool] = mapped_column(default=True, nullable=False)

    # Timestamps
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )

    # Relationships
    user: Mapped["User"] = relationship("User", back_populates="devices")

    def __repr__(self) -> str:
        return f"<Device(id={self.id}, uuid={self.device_uuid[:8]}..., name={self.device_name})>"

    def update_last_seen(self) -> None:
        """Update the last seen timestamp to current UTC time."""
        from datetime import timezone
        self.last_seen = datetime.now(timezone.utc)
