"""Device management schemas for CLI registration and tracking.

Validates device information and enforces tier-based device limits.
"""

from datetime import datetime
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, field_validator


class DeviceCreate(BaseModel):
    """Device registration request.

    CLI sends this to register a new device installation.
    """

    device_uuid: str = Field(
        ...,
        min_length=16,
        max_length=255,
        description="Unique device identifier (generated by CLI)",
    )
    device_name: str = Field(
        ...,
        min_length=1,
        max_length=255,
        description="User-friendly device name",
    )
    platform: Literal["linux", "darwin", "win32"] | None = Field(
        None,
        description="Operating system platform",
    )
    hostname: str | None = Field(
        None,
        max_length=255,
        description="Machine hostname",
    )

    @field_validator("device_name")
    @classmethod
    def validate_device_name(cls, v: str) -> str:
        """Ensure device name is not empty or whitespace only."""
        if not v.strip():
            raise ValueError("Device name cannot be empty or whitespace")
        return v.strip()


class DeviceUpdate(BaseModel):
    """Device update request.

    Allows updating device name and activity status.
    """

    device_name: str | None = Field(
        None,
        min_length=1,
        max_length=255,
        description="Updated device name",
    )
    is_active: bool | None = Field(
        None,
        description="Device active status",
    )


class DeviceResponse(BaseModel):
    """Device information response.

    Returns device details with timestamps.
    """

    model_config = ConfigDict(from_attributes=True)

    id: int
    user_id: int
    device_uuid: str
    device_name: str
    platform: str | None = None
    hostname: str | None = None
    last_seen: datetime
    is_active: bool
    created_at: datetime
    updated_at: datetime


class DeviceListResponse(BaseModel):
    """List of user devices with metadata."""

    devices: list[DeviceResponse]
    total: int = Field(..., description="Total number of devices")
    active_count: int = Field(..., description="Number of active devices")
    device_limit: int = Field(..., description="Device limit for user's tier")


class DeviceLimitInfo(BaseModel):
    """Device limit information per tier."""

    tier: Literal["free", "starter", "pro", "enterprise"]
    limit: int = Field(..., description="Maximum number of devices allowed")
    current: int = Field(..., description="Current number of active devices")
    remaining: int = Field(..., description="Remaining device slots")
    can_add: bool = Field(..., description="Whether user can add more devices")


# Tier-based device limits
DEVICE_LIMITS = {
    "free": 1,
    "starter": 2,
    "pro": 3,
    "enterprise": 999999,  # Effectively unlimited
}


def get_device_limit(tier: str) -> int:
    """Get device limit for a subscription tier.

    Args:
        tier: Subscription tier name

    Returns:
        Maximum number of devices allowed for the tier
    """
    return DEVICE_LIMITS.get(tier, 1)  # Default to free tier limit
