// Code generated by protoc-gen-go. DO NOT EDIT.
// This is a stub file - in production, this would be generated from crawler.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
)

// Timestamp represents a timestamp
type Timestamp struct {
	Seconds int64
	Nanos   int32
}

// HealthCheckRequest message
type HealthCheckRequest struct{}

// HealthCheckResponse message
type HealthCheckResponse struct {
	Status        string
	ServiceName   string
	Version       string
	UptimeSeconds int64
}

// CrawlRequest message
type CrawlRequest struct {
	Url     string
	Options *CrawlOptions
}

// CrawlOptions message
type CrawlOptions struct {
	MaxDepth            int32
	MaxPages            int32
	FollowExternalLinks bool
	RespectRobotsTxt    bool
	AllowedDomains      []string
	ExcludedPaths       []string
	ConcurrentRequests  int32
	DelayMs             int32
	UserAgent           string
	JavascriptRendering bool
	CustomHeaders       map[string]string
}

// CrawlResult message
type CrawlResult struct {
	Url        string
	StatusCode int32
	Headers    map[string]string
	Depth      int32
	Timestamp  *Timestamp
}

// ExtractRequest message
type ExtractRequest struct {
	Url                 string
	Selectors           []*Selector
	JavascriptRendering bool
}

// Selector message
type Selector struct {
	Name        string
	CssSelector string
	Xpath       string
	Attribute   string
	Multiple    bool
}

// ExtractResponse message
type ExtractResponse struct {
	Status *Status
	Data   map[string]*ExtractedData
}

// Status message
type Status struct {
	Success bool
	Message string
}

// ExtractedData message
type ExtractedData struct {
	Values []string
}

// ScreenshotRequest message
type ScreenshotRequest struct {
	Url     string
	Options *ScreenshotOptions
}

// ScreenshotOptions message
type ScreenshotOptions struct {
	Width           int32
	Height          int32
	FullPage        bool
	Quality         int32
	Format          string
	WaitMs          int32
	WaitForSelector string
}

// ScreenshotResponse message
type ScreenshotResponse struct {
	Status    *Status
	ImageData []byte
	Format    string
	Width     int32
	Height    int32
}

// SubdomainRequest message
type SubdomainRequest struct {
	Domain  string
	Sources []string
}

// SubdomainResponse message
type SubdomainResponse struct {
	Status     *Status
	Subdomains []*SubdomainInfo
}

// SubdomainInfo message
type SubdomainInfo struct {
	Subdomain   string
	IpAddresses []string
	Source      string
	Active      bool
}

// RobotsTxtRequest message
type RobotsTxtRequest struct {
	Url       string
	UserAgent string
}

// RobotsTxtResponse message
type RobotsTxtResponse struct {
	Status          *Status
	Exists          bool
	Content         string
	DisallowedPaths []string
	AllowedPaths    []string
	Sitemaps        []string
	CrawlDelay      int32
}

// WebCrawlerClient is the client API for WebCrawler service.
type WebCrawlerClient interface {
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
	CrawlWebsite(ctx context.Context, in *CrawlRequest, opts ...grpc.CallOption) (WebCrawler_CrawlWebsiteClient, error)
	ExtractData(ctx context.Context, in *ExtractRequest, opts ...grpc.CallOption) (*ExtractResponse, error)
	TakeScreenshot(ctx context.Context, in *ScreenshotRequest, opts ...grpc.CallOption) (*ScreenshotResponse, error)
	FindSubdomains(ctx context.Context, in *SubdomainRequest, opts ...grpc.CallOption) (*SubdomainResponse, error)
	CheckRobotsTxt(ctx context.Context, in *RobotsTxtRequest, opts ...grpc.CallOption) (*RobotsTxtResponse, error)
}

// WebCrawler_CrawlWebsiteClient is the client for streaming CrawlWebsite
type WebCrawler_CrawlWebsiteClient interface {
	Recv() (*CrawlResult, error)
	grpc.ClientStream
}

// WebCrawlerServer is the server API for WebCrawler service.
type WebCrawlerServer interface {
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	CrawlWebsite(*CrawlRequest, WebCrawler_CrawlWebsiteServer) error
	ExtractData(context.Context, *ExtractRequest) (*ExtractResponse, error)
	TakeScreenshot(context.Context, *ScreenshotRequest) (*ScreenshotResponse, error)
	FindSubdomains(context.Context, *SubdomainRequest) (*SubdomainResponse, error)
	CheckRobotsTxt(context.Context, *RobotsTxtRequest) (*RobotsTxtResponse, error)
}

// WebCrawler_CrawlWebsiteServer is the server for streaming CrawlWebsite
type WebCrawler_CrawlWebsiteServer interface {
	Send(*CrawlResult) error
	grpc.ServerStream
}

// UnimplementedWebCrawlerServer can be embedded to have forward compatible implementations.
type UnimplementedWebCrawlerServer struct{}

func (*UnimplementedWebCrawlerServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, nil
}

func (*UnimplementedWebCrawlerServer) CrawlWebsite(*CrawlRequest, WebCrawler_CrawlWebsiteServer) error {
	return nil
}

func (*UnimplementedWebCrawlerServer) ExtractData(context.Context, *ExtractRequest) (*ExtractResponse, error) {
	return nil, nil
}

func (*UnimplementedWebCrawlerServer) TakeScreenshot(context.Context, *ScreenshotRequest) (*ScreenshotResponse, error) {
	return nil, nil
}

func (*UnimplementedWebCrawlerServer) FindSubdomains(context.Context, *SubdomainRequest) (*SubdomainResponse, error) {
	return nil, nil
}

func (*UnimplementedWebCrawlerServer) CheckRobotsTxt(context.Context, *RobotsTxtRequest) (*RobotsTxtResponse, error) {
	return nil, nil
}

// RegisterWebCrawlerServer registers the WebCrawler service
func RegisterWebCrawlerServer(s *grpc.Server, srv WebCrawlerServer) {
	// Registration would happen here
} 