package tui

// Custom message types for TUI inter-component communication
// These messages are passed through the Bubble Tea update loop to coordinate
// actions between different views and components.

// ScanStartMsg triggers a new security scan
// Sent when the user initiates a scan from the scan view
type ScanStartMsg struct {
	Target   string // Target hostname, IP, or CIDR range
	ScanType string // Type of scan: "quick", "full", "stealth", etc.
}

// ScanOutputMsg contains real-time scan output
// Sent continuously during an active scan to display progress
type ScanOutputMsg struct {
	Line string // Single line of scan output (e.g., from nmap)
	Raw  bool   // Whether to display as raw terminal output or parsed
}

// ScanCompleteMsg signals scan completion
// Sent when a scan finishes (either successfully or with error)
type ScanCompleteMsg struct {
	Success bool  // Whether the scan completed successfully
	Error   error // Error details if scan failed (nil on success)
}

// AIResponseMsg contains AI-generated analysis or response
// Sent when the AI has finished processing a user query
type AIResponseMsg struct {
	Response string // AI-generated text response
	Error    error  // Error if AI request failed (nil on success)
}

// AIRequestMsg triggers an AI query
// Sent when user submits a question to the AI panel
type AIRequestMsg struct {
	Query   string // User's question or prompt
	Context string // Current view context for better AI responses
}

// ViewChangeMsg requests a view change
// Used internally to switch between different TUI views
type ViewChangeMsg struct {
	View View // Target view to switch to (ViewDashboard, ViewScan, etc.)
}

// StatusUpdateMsg updates the status bar message
// Used to show transient status information to the user
type StatusUpdateMsg struct {
	Message string // Status message to display
}

// ErrorMsg displays an error notification
// Used to show errors in a user-friendly way
type ErrorMsg struct {
	Title   string // Error title (e.g., "Scan Failed")
	Message string // Detailed error message
	Err     error  // Underlying error object (optional)
}

// SuccessMsg displays a success notification
// Used to show positive feedback to the user
type SuccessMsg struct {
	Title   string // Success title (e.g., "Scan Complete")
	Message string // Success details
}

// LoadHistoryMsg triggers loading of scan history
// Sent when history view needs to refresh its data
type LoadHistoryMsg struct {
	Limit int // Maximum number of history entries to load (0 = all)
}

// HistoryLoadedMsg contains loaded history data
// Sent when history has been successfully loaded from database
type HistoryLoadedMsg struct {
	// History items would be defined in a separate history package
	// This is a placeholder for the actual history data structure
	Count int // Number of history items loaded
}

// ReconStartMsg triggers a reconnaissance operation
// Sent when user initiates recon from the recon view
type ReconStartMsg struct {
	Target     string   // Target domain or IP
	ReconTypes []string // Types of recon to perform (subdomain, dns, whois, etc.)
}

// ReconResultMsg contains reconnaissance results
// Sent when a recon operation completes or produces results
type ReconResultMsg struct {
	ReconType string      // Type of recon (subdomain, dns, whois, etc.)
	Data      interface{} // Recon data (type varies by recon type)
	Error     error       // Error if recon failed (nil on success)
}

// EnqueueScanMsg requests a new scan to be added to the queue
// Sent from scan/recon views when user initiates a scan
type EnqueueScanMsg struct {
	ID     string // Unique job ID (generated by caller)
	Target string // Scan target (IP, domain, CIDR, URL)
	Tool   string // Tool to use (nmap, nikto, etc.)
	Phase  string // Optional recon phase identifier
}
