name: Python Tests

on:
  push:
    branches: [ main, develop, Zypheron-CLI ]
  pull_request:
    branches: [ main, develop, Zypheron-CLI ]

jobs:
  test:
    name: Run Python Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11']
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Cache Python packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      
      - name: Install dependencies
        run: |
          cd zypheron-ai
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e ".[test]"
      
      - name: Run tests with coverage
        run: |
          cd zypheron-ai
          pytest --cov=. --cov-report=xml --cov-report=term-missing
      
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./zypheron-ai/coverage.xml
          flags: python
          name: python-coverage
          fail_ci_if_error: false

